# Generated by Django 4.2.7 on 2023-12-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_thefriends_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thefriends',
            name='lise',
        ),
        migrations.AddField(
            model_name='thefriends',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thefriends',
            name='username',
            field=models.CharField(default='default_username', max_length=255, unique=True),
        ),
    ]
